In [27]:
import numpy as np
from numpy import random

# ASSIGNMENT

1. Create a 4x4 matrix with values ranging from 0 to 3.\
(The following image is just as an example. It doesn't represent the real image of arrays in the question)
![](image/assignment2.png)

In [29]:
a = random.randint(0,4,(4,4))
a

array([[1, 1, 1, 3],
       [2, 0, 2, 3],
       [2, 0, 0, 0],
       [2, 0, 1, 0]])

2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.\
![](image/assignment.png)

In [85]:
b = np.hsplit(a,2)
b

[array([[1, 1],
       [2, 0],
       [2, 0],
       [2, 0]]), array([[1, 3],
       [2, 3],
       [0, 0],
       [1, 0]])]


3. soal tambahan:

misalkan kita memiliki data array seperti berikut ini :

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
       
tuliskan proses filtering untuk mendapatkan hanya elemen data yang berupa bilangan prima ? 

jika dilihat dari data, output yang diinginkan : 2, 3, 7, 11, 13, 17, 19, 23

In [307]:
c = np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [325]:
output = np.array([])

def prime(n):
    if n == 1:
        return False
    for d in range(2,n):
        if n % d == 0:
            return False
    return True

for row in c:
    for elm in row:
        if prime(elm) is True:
            output = np.append(output, elm)
            output = output.astype(int)
            
output

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23])